version: "3.3"

services:
  app:
    build: ./
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - "80:8000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - data1:/var/lib/postgresql/data

volumes:
  data1:
