# Generated by Django 4.1.1 on 2022-12-26 21:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import social_manager_api.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_manager_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TikTok', 'Tik Tok'), ('Instagram', 'Instagram'), ('Telegram', 'Telegram')], max_length=20)),
                ('token', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('hash_tag', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=social_manager_api.models.get_upload_path)),
                ('video', models.FileField(blank=True, null=True, upload_to=social_manager_api.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov'])])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_manager_api.account')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='A',
        ),
    ]
