# Generated by Django 4.1.4 on 2023-01-14 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_manager_api', '0002_account_post_delete_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parse_mode',
            field=models.CharField(blank=True, choices=[('DEFAULT', 'Default'), ('MARKDOWN', 'Markdown'), ('HTML', 'Html'), ('DISABLED', 'Disabled')], default='DEFAULT', max_length=20),
        ),
        migrations.RemoveField(
            model_name='post',
            name='account',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.TextField()),
                ('account_type', models.CharField(choices=[('TikTok', 'Tik Tok'), ('Instagram', 'Instagram'), ('Telegram', 'Telegram')], max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_manager_api.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='account',
            field=models.ManyToManyField(to='social_manager_api.account'),
        ),
    ]
