# Generated by Django 4.1.4 on 2023-01-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_manager_api', '0003_post_parse_mode_remove_post_account_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='post',
            name='parse_mode',
            field=models.CharField(blank=True, choices=[('DEFAULT', 'Default'), ('MARKDOWN', 'Markdown'), ('HTML', 'Html'), ('DISABLED', 'Disabled')], default=None, max_length=20),
        ),
    ]
