# Generated by Django 4.1.4 on 2023-01-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_manager_api', '0005_alter_account_unique_together_chat_message_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='account',
            new_name='accounts',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='post',
        ),
        migrations.RemoveField(
            model_name='message',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='chats',
            field=models.ManyToManyField(to='social_manager_api.chat'),
        ),
        migrations.AddField(
            model_name='post',
            name='message_ids',
            field=models.ManyToManyField(to='social_manager_api.message'),
        ),
    ]
