# Generated by Django 4.1.7 on 2023-02-26 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_manager_api', '0007_chat_user_message_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='user', max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('name', 'user')},
        ),
    ]
