# Generated by Django 4.1.7 on 2023-02-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_manager_api', '0008_alter_account_unique_together_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
