# Generated by Django 4.1.7 on 2023-02-27 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_manager_api', '0009_alter_account_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='account_type',
        ),
        migrations.AddField(
            model_name='chat',
            name='account',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='social_manager_api.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='account',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='social_manager_api.account'),
            preserve_default=False,
        ),
    ]
